### PR TITLE
Make Sigar not optional because it is now used in most Monitors

### PR DESCRIPTION
**Pull request by leventov**

### CODE REVIEW

**Comment by drcrallen** [comment]
👍

**Comment by drcrallen** [comment]
We should bump a bigger version for this one's release

**Comment by leventov** [comment]
@drcallen please don't hurry with a release. I'm going to make more changes before it next week.

**Comment by drcrallen** [comment]
Ok, since the release procedure is more fast and loose for this repo I propose leaving this PR open and the last one to be merged before the next release.

**Pull request merged**
